#!/usr/bin/env python3
"""
polybot - CLI for managing Polymarket follower bot instances.

Commands:
    search       Search for high-quality copy-trading targets
    add          Add a new bot instance
    list         List all bot instances
    start        Start a bot instance
    stop         Stop a bot instance
    restart      Restart a bot instance
    logs         View bot logs
    status       Show bot status
    remove       Remove a bot instance
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Paths
REPO_ROOT = Path(__file__).resolve().parent.parent
BOTS_DIR = REPO_ROOT / "docker" / "bots"
DOCKER_DIR = REPO_ROOT / "docker"
COMPOSE_FILE = DOCKER_DIR / "docker-compose.yml"
ENV_EXAMPLE = REPO_ROOT / "src" / ".env.example"


def run_cmd(cmd, capture=True):
    """Run a shell command."""
    if capture:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        return result.returncode, result.stdout, result.stderr
    else:
        return subprocess.run(cmd, shell=True).returncode, "", ""


def docker_compose(*args):
    """Run docker compose in the docker directory."""
    cmd = f"cd {DOCKER_DIR} && docker compose {' '.join(args)}"
    code, out, err = run_cmd(cmd)
    if err and "error" in err.lower():
        print(f"Error: {err.strip()}", file=sys.stderr)
    return code, out, err


def load_compose():
    """Load docker-compose.yml."""
    if not COMPOSE_FILE.exists():
        return {}
    # Simple YAML parsing without pyyaml dependency
    # We'll just manage it as text with markers
    return COMPOSE_FILE.read_text()


def save_compose(content):
    """Save docker-compose.yml."""
    COMPOSE_FILE.parent.mkdir(parents=True, exist_ok=True)
    COMPOSE_FILE.write_text(content)


def get_bot_names():
    """Get list of configured bot names from bots/ directory."""
    if not BOTS_DIR.exists():
        return []
    return [d.name for d in BOTS_DIR.iterdir() if d.is_dir() and (d / ".env").exists()]


def generate_compose_service(name):
    """Generate a docker-compose service block for a bot."""
    return f"""  {name}:
    build: ..
    container_name: polybot-{name}
    restart: always
    env_file:
      - bots/{name}/.env
    volumes:
      - {name}-config:/app/config
      - {name}-logs:/app/logs
    environment:
      - FOLLOWER_CHECK_INTERVAL_MINUTES=5"""


def regenerate_compose():
    """Regenerate docker-compose.yml from all bot directories."""
    bots = get_bot_names()
    if not bots:
        services = ""
    else:
        services = "\n\n".join(generate_compose_service(b) for b in bots)

    volumes = "\n".join(f"  {b}-config:" for b in bots) if bots else ""
    volume_logs = "\n".join(f"  {b}-logs:" for b in bots) if bots else ""
    if volumes and volume_logs:
        volumes = volumes + "\n" + volume_logs

    content = f"""services:
  # ============================================================
  # Polymarket Follower Bot - Multi-Instance Docker Compose
  # ============================================================
  # Auto-generated by polybot CLI. Do not edit manually.
  # Use: python cli/polybot.py add/remove to manage bots.
  # ============================================================

{services}

volumes:
{volumes if volumes else "  # No volumes configured"}
"""
    save_compose(content)


# ============================================================
# Commands
# ============================================================

def cmd_search(args):
    """Search for high-quality copy-trading targets."""
    search_script = REPO_ROOT / "cli" / "search.py"
    cmd = f"python3 {search_script}"
    for flag in ["min-pnl", "min-roi", "min-vol", "min-win-rate", "sort", "limit", "leaderboard-size"]:
        val = getattr(args, flag.replace("-", "_"), None)
        if val is not None:
            cmd += f" --{flag} {val}"
    if args.deep:
        cmd += " --deep"
    if args.json:
        cmd += " --json"
    os.system(cmd)


def cmd_add(args):
    """Add a new bot instance."""
    name = args.name
    target = args.target
    api_key = args.api_key
    secret = args.secret
    passphrase = args.passphrase
    private_key = args.private_key
    funder = args.funder

    if not all([target, api_key, secret, passphrase, private_key, funder]):
        print("All credentials are required. Use: polybot add <name> --target ADDR --api-key KEY --secret SECRET --passphrase PHRASE --private-key KEY --funder ADDR")
        sys.exit(1)

    bot_dir = BOTS_DIR / name
    bot_dir.mkdir(parents=True, exist_ok=True)

    env_content = f"""POLY_MARKET_API_KEY={api_key}
POLY_MARKET_SECRET={secret}
POLY_MARKET_PASSPHRASE={passphrase}

PRIVATE_KEY={private_key}

POLY_MARKET_FUNDER_ADDRESS={funder}

# Target address to follow
ADDRESS_TO_FOLLOW={target}
"""

    (bot_dir / ".env").write_text(env_content)
    print(f"Created {bot_dir / '.env'}")

    # Regenerate docker-compose.yml
    regenerate_compose()
    print(f"Updated docker-compose.yml")

    print(f"\nBot '{name}' added! To start it:")
    print(f"  python cli/polybot.py start {name}")


def cmd_list(args):
    """List all bot instances."""
    bots = get_bot_names()
    if not bots:
        print("No bots configured.")
        print("Use: python cli/polybot.py add <name> --target ADDR ...")
        return

    # Check status of each
    print(f"{'Name':<20} {'Container':<25} {'Status':<15} {'Target'}")
    print("-" * 80)
    for name in bots:
        # Check container status
        code, out, _ = run_cmd(f"docker inspect --format '{{{{.State.Status}}}}' polybot-{name} 2>/dev/null")
        status = out.strip() if code == 0 else "not running"

        # Read target from .env
        env_file = BOTS_DIR / name / ".env"
        target = ""
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                if line.startswith("ADDRESS_TO_FOLLOW="):
                    target = line.split("=", 1)[1][:16] + "..."
                    break

        print(f"{name:<20} polybot-{name:<15} {status:<15} {target}")


def cmd_start(args):
    """Start a bot instance."""
    name = args.name
    if name == "all":
        code, _, _ = docker_compose("up", "-d", "--build")
    else:
        code, _, _ = docker_compose("up", "-d", "--build", name)
    if code == 0:
        print(f"Bot '{name}' started.")
    else:
        print(f"Failed to start bot '{name}'.", file=sys.stderr)


def cmd_stop(args):
    """Stop a bot instance."""
    name = args.name
    if name == "all":
        code, _, _ = docker_compose("down")
    else:
        code, _, _ = docker_compose("stop", name)
    if code == 0:
        print(f"Bot '{name}' stopped.")
    else:
        print(f"Failed to stop bot '{name}'.", file=sys.stderr)


def cmd_restart(args):
    """Restart a bot instance."""
    name = args.name
    if name == "all":
        code, _, _ = docker_compose("restart")
    else:
        code, _, _ = docker_compose("restart", name)
    if code == 0:
        print(f"Bot '{name}' restarted.")
    else:
        print(f"Failed to restart bot '{name}'.", file=sys.stderr)


def cmd_logs(args):
    """View bot logs."""
    name = args.name
    lines = args.lines or 50
    follow = "-f" if args.follow else ""
    os.system(f"cd {DOCKER_DIR} && docker compose logs {follow} --tail {lines} {name}")


def cmd_status(args):
    """Show detailed bot status."""
    name = args.name
    code, out, err = run_cmd(f"docker inspect --format '{{{{.State.Status}}}}' polybot-{name} 2>/dev/null")
    if code != 0:
        print(f"Bot '{name}' is not running.")
        return

    status = out.strip()
    print(f"Bot: {name}")
    print(f"Container: polybot-{name}")
    print(f"Status: {status}")

    # Show recent logs
    code, out, _ = docker_compose("logs", "--tail", "10", name)
    if out:
        print(f"\nRecent logs:")
        print(out)


def cmd_remove(args):
    """Remove a bot instance."""
    name = args.name

    # Stop first
    docker_compose("stop", name)
    docker_compose("rm", "-f", name)

    # Remove bot directory
    bot_dir = BOTS_DIR / name
    if bot_dir.exists():
        shutil.rmtree(bot_dir)
        print(f"Removed {bot_dir}")

    # Regenerate compose
    regenerate_compose()
    print(f"Bot '{name}' removed.")


def main():
    parser = argparse.ArgumentParser(
        description="polybot - Manage Polymarket follower bot instances"
    )
    subparsers = parser.add_subparsers(dest="command", help="Command")

    # search
    p = subparsers.add_parser("search", help="Search for high-quality targets")
    p.add_argument("--min-pnl", type=float, default=0)
    p.add_argument("--min-roi", type=float, default=0)
    p.add_argument("--min-vol", type=float, default=0)
    p.add_argument("--min-win-rate", type=float, default=0)
    p.add_argument("--sort", type=str, default="composite_score",
                    choices=["composite_score", "pnl", "roi", "win_rate", "consistency_score", "rank"])
    p.add_argument("--limit", type=int, default=20)
    p.add_argument("--leaderboard-size", type=int, default=100)
    p.add_argument("--deep", action="store_true")
    p.add_argument("--json", action="store_true", dest="as_json")

    # add
    p = subparsers.add_parser("add", help="Add a new bot instance")
    p.add_argument("name", help="Bot instance name")
    p.add_argument("--target", required=True, help="Target address to follow")
    p.add_argument("--api-key", required=True, help="CLOB API key")
    p.add_argument("--secret", required=True, help="CLOB API secret")
    p.add_argument("--passphrase", required=True, help="CLOB API passphrase")
    p.add_argument("--private-key", required=True, help="Private key")
    p.add_argument("--funder", required=True, help="Funder/proxy wallet address")

    # list
    subparsers.add_parser("list", help="List all bot instances")

    # start
    p = subparsers.add_parser("start", help="Start a bot")
    p.add_argument("name", help="Bot name or 'all'")

    # stop
    p = subparsers.add_parser("stop", help="Stop a bot")
    p.add_argument("name", help="Bot name or 'all'")

    # restart
    p = subparsers.add_parser("restart", help="Restart a bot")
    p.add_argument("name", help="Bot name or 'all'")

    # logs
    p = subparsers.add_parser("logs", help="View bot logs")
    p.add_argument("name", help="Bot name")
    p.add_argument("-f", "--follow", action="store_true", help="Follow logs")
    p.add_argument("--lines", type=int, default=50, help="Number of lines")

    # status
    p = subparsers.add_parser("status", help="Show bot status")
    p.add_argument("name", help="Bot name")

    # remove
    p = subparsers.add_parser("remove", help="Remove a bot instance")
    p.add_argument("name", help="Bot name")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    commands = {
        "search": cmd_search,
        "add": cmd_add,
        "list": cmd_list,
        "start": cmd_start,
        "stop": cmd_stop,
        "restart": cmd_restart,
        "logs": cmd_logs,
        "status": cmd_status,
        "remove": cmd_remove,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
