#!/usr/bin/env python3
"""
polybot - CLI for managing Polymarket follower bot instances.

Commands:
    search       Search for high-quality copy-trading targets
    setup        Generate wallet and configure a new bot
    add          Add a new bot instance from an env file
    edit         Edit a bot instance (interactive menu)
    list         List all bot instances
    start        Start a bot instance
    stop         Stop a bot instance
    restart      Restart a bot instance
    logs         View bot logs
    status       Show bot status
    remove       Remove a bot instance
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path

VENV_SITE = str(Path(__file__).resolve().parent.parent / "src" / "venv" / "lib")
for p in sorted(Path(VENV_SITE).glob("python*/site-packages"), reverse=True):
    if p.exists():
        sys.path.insert(0, str(p))
        break

import re

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
BOTS_DIR = REPO_ROOT / "docker" / "bots"
DOCKER_DIR = REPO_ROOT / "docker"
COMPOSE_FILE = DOCKER_DIR / "docker-compose.yml"
ENV_EXAMPLE = REPO_ROOT / "src" / ".env.example"
DOCKER_ENV = DOCKER_DIR / ".env"

SPINNER_CHARS = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"


def clear_screen():
    print("\033[2J\033[H", end="", flush=True)


def spinner(msg, event):
    i = 0
    while not event.is_set():
        print(f"\r  {SPINNER_CHARS[i % len(SPINNER_CHARS)]} {msg}", end="", flush=True)
        i += 1
        time.sleep(0.08)
    print(f"\r  ✔ {msg}")


def run_spinner(msg, fn, *args, **kwargs):
    event = threading.Event()
    t = threading.Thread(target=spinner, args=(msg, event), daemon=True)
    t.start()
    try:
        result = fn(*args, **kwargs)
    except Exception as e:
        event.set()
        t.join()
        print(f"\r  ✖ {msg}")
        raise
    event.set()
    t.join()
    return result


def run_cmd(cmd, capture=True):
    if capture:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        return result.returncode, result.stdout, result.stderr
    else:
        return subprocess.run(cmd, shell=True).returncode, "", ""


def docker_compose(*args):
    cmd = f"cd {DOCKER_DIR} && docker compose {' '.join(args)}"
    code, out, err = run_cmd(cmd)
    return code, out, err


def load_compose():
    if not COMPOSE_FILE.exists():
        return {}
    return COMPOSE_FILE.read_text()


def save_compose(content):
    COMPOSE_FILE.parent.mkdir(parents=True, exist_ok=True)
    COMPOSE_FILE.write_text(content)


def get_bot_names():
    if not BOTS_DIR.exists():
        return []
    return [d.name for d in BOTS_DIR.iterdir() if d.is_dir() and (d / ".env").exists()]


def generate_compose_service(name):
    return f"""  {name}:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: polybot-{name}
    restart: always
    env_file:
      - .env
      - bots/{name}/.env
    volumes:
      - {name}-config:/app/config
      - {name}-logs:/app/logs
    environment:
      - FOLLOWER_CHECK_INTERVAL_MINUTES=5"""


def regenerate_compose():
    bots = get_bot_names()
    if not bots:
        services = ""
    else:
        services = "\n\n".join(generate_compose_service(b) for b in bots)

    volumes = "\n".join(f"  {b}-config:" for b in bots) if bots else ""
    volume_logs = "\n".join(f"  {b}-logs:" for b in bots) if bots else ""
    if volumes and volume_logs:
        volumes = volumes + "\n" + volume_logs

    content = f"""name: polymarket-swarm

services:
  # ============================================================
  # Polymarket Follower Bot - Multi-Instance Docker Compose
  # ============================================================
  # Auto-generated by polybot CLI. Do not edit manually.
  # Use: python cli/polybot.py add/remove to manage bots.
  # ============================================================

{services}

volumes:
{volumes if volumes else "  # No volumes configured"}
"""
    save_compose(content)


def parse_env_file(path):
    env = {}
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        env[key] = value
    return env


# ============================================================
# Commands
# ============================================================

def cmd_search(args):
    search_script = REPO_ROOT / "cli" / "search.py"
    cmd = f"python3 {search_script}"
    for flag in ["min-pnl", "min-roi", "min-win-rate", "min-markets", "sort", "limit",
                  "leaderboard-pages", "workers", "max-candidates", "max-days-inactive"]:
        val = getattr(args, flag.replace("-", "_"), None)
        if val is not None:
            cmd += f" --{flag} {val}"
    if args.deep:
        cmd += " --deep"
    if args.as_json:
        cmd += " --json"
    if getattr(args, "categories", None) and args.categories != "OVERALL":
        cmd += f" --categories {args.categories}"
    os.system(cmd)


REQUIRED_ENV_VARS = {
    "BOT_NAME": None,
    "BOT_USERNAME": None,
    "PRIVATE_KEY": None,
    "TARGET_ADDRESS": None,
    "TARGET_USERNAME": None,
    "POLY_MARKET_API_KEY": None,
    "POLY_MARKET_SECRET": None,
    "POLY_MARKET_PASSPHRASE": None,
    "POLY_MARKET_FUNDER_ADDRESS": None,
}


def fetch_profile(address):
    """Fetch Polymarket profile by wallet address. Returns username or None."""
    try:
        resp = requests.get(
            "https://gamma-api.polymarket.com/public-profile",
            params={"address": address},
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            return data.get("name") or data.get("pseudonym")
    except Exception:
        pass
    return None


def cmd_setup(args):
    """Generate wallet and configure a new bot."""
    print()
    print("🤖  Polymarket Follower Bot Setup")
    print("=" * 40)
    print()
    print("  First, create a fresh Polymarket account at:")
    print("  👉 https://polymarket.com")
    print()
    print("  After signing up, come back here with:")
    print("  - Your private key (from wallet settings)")
    print("  - Your funder/proxy address (from https://polymarket.com/settings)")
    print("  - The target address you want to follow")
    print()

    bot_name = args.name
    if not bot_name:
        bot_name = input("  📛 Bot name: ").strip()
        if not bot_name:
            print("  ✖ Bot name is required", file=sys.stderr)
            sys.exit(1)
    if not re.match(r'^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$', bot_name):
        print("  ✖ Bot name must be lowercase alphanumeric with hyphens (no leading/trailing hyphens)", file=sys.stderr)
        sys.exit(1)

    private_key = args.private_key
    if not private_key:
        private_key = input("  🔑 Private key: ").strip()
    if not private_key:
        print("  ✖ Private key is required", file=sys.stderr)
        sys.exit(1)

    funder_address = args.funder
    if not funder_address:
        funder_address = input("  💰 Funder/proxy address (0x...): ").strip()
    if not funder_address.startswith("0x") or len(funder_address) != 42:
        print("  ✖ Invalid funder address", file=sys.stderr)
        sys.exit(1)

    target_address = args.target
    if not target_address:
        target_address = input("  🎯 Target address to follow (0x...): ").strip()
    if not target_address.startswith("0x") or len(target_address) != 42:
        print("  ✖ Invalid target address", file=sys.stderr)
        sys.exit(1)

    print()

    bot_username = fetch_profile(funder_address) or ""
    target_username = fetch_profile(target_address) or ""

    if bot_username:
        print(f"  ✔ Bot username: {bot_username}")
    else:
        print("  ⚠ Could not fetch bot username — set BOT_USERNAME manually later")

    if target_username:
        print(f"  ✔ Target username: {target_username}")
    else:
        print("  ⚠ Could not fetch target username — set TARGET_USERNAME manually later")

    def create_creds():
        from py_clob_client_v2 import ClobClient
        client = ClobClient(
            host="https://clob.polymarket.com",
            chain_id=137,
            key=private_key,
        )
        return client.create_or_derive_api_key()

    creds = run_spinner("Creating API credentials", create_creds)
    try:
        api_key = creds["apiKey"]
        api_secret = creds["secret"]
        api_passphrase = creds["passphrase"]
    except TypeError:
        api_key = creds.api_key
        api_secret = creds.api_secret
        api_passphrase = creds.api_passphrase
    print(f"    API key: {api_key}")

    env_data = {
        "BOT_NAME": bot_name,
        "BOT_USERNAME": bot_username,
        "PRIVATE_KEY": private_key,
        "TARGET_ADDRESS": target_address,
        "TARGET_USERNAME": target_username,
        "POLY_MARKET_API_KEY": api_key,
        "POLY_MARKET_SECRET": api_secret,
        "POLY_MARKET_PASSPHRASE": api_passphrase,
        "POLY_MARKET_FUNDER_ADDRESS": funder_address,
    }

    bot_dir = BOTS_DIR / bot_name
    bot_dir.mkdir(parents=True, exist_ok=True)
    write_env_file(env_data, bot_dir / ".env")

    regenerate_compose()

    print()
    print("=" * 40)
    print(f"  ✔ Bot '{bot_name}' configured!")
    print()
    print("  📋 Remaining manual steps:")
    print()
    print("  1. Approve trading & auto-redeem in the Polymarket UI")
    print("  2. Deposit pUSD into your account")
    print()
    print(f"  Then start the bot:")
    print(f"  👉 python cli/polybot.py start {bot_name}")
    print()


def cmd_add(args):
    env_path = Path(args.env_file)
    if not env_path.exists():
        print(f"✖ File not found: {env_path}", file=sys.stderr)
        sys.exit(1)

    env = parse_env_file(env_path)

    if "ADDRESS_TO_FOLLOW" in env and "TARGET_ADDRESS" not in env:
        env["TARGET_ADDRESS"] = env.pop("ADDRESS_TO_FOLLOW")

    missing = [k for k, v in REQUIRED_ENV_VARS.items() if k not in env]
    if missing:
        print(f"✖ Missing required vars in env file: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)

    name = env["BOT_NAME"]

    bot_dir = BOTS_DIR / name
    bot_dir.mkdir(parents=True, exist_ok=True)

    write_env_file(env, bot_dir / ".env")
    print(f"✔ Created {bot_dir / '.env'}")

    regenerate_compose()
    print("✔ Updated docker-compose.yml")

    print(f"\n🤖 Bot '{name}' added! To start it:")
    print(f"  python cli/polybot.py start {name}")


def fetch_portfolio_value(address):
    try:
        resp = requests.get(
            "https://data-api.polymarket.com/value",
            params={"user": address},
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            if isinstance(data, list) and data:
                return float(data[0].get("value", 0))
        return 0.0
    except Exception:
        return 0.0


PUSD_CONTRACT = "0xc011a7e12a19f7b1f670d46f03b03f3342e82dfb"


def fetch_cash_balance(address):
    if not DOCKER_ENV.exists():
        return 0.0
    docker_env = parse_env_file(DOCKER_ENV)
    etherscan_key = docker_env.get("ETHERSCAN_API_KEY", "")
    if not etherscan_key or not address:
        return 0.0
    try:
        resp = requests.get(
            "https://api.etherscan.io/v2/api",
            params={
                "chainid": 137,
                "module": "account",
                "action": "tokenbalance",
                "contractaddress": PUSD_CONTRACT,
                "address": address,
                "tag": "latest",
                "apikey": etherscan_key,
            },
            timeout=10,
        )
        data = resp.json()
        result = data.get("result", "0")
        if not result or not result.isdigit():
            return 0.0
        return int(result) / 10**6
    except Exception:
        return 0.0


def cmd_list(args):
    bots = get_bot_names()
    if not bots:
        print("No bots configured. Use: python cli/polybot.py setup")
        return

    def collect_data():
        rows = []
        total_portfolio = 0.0
        total_cash = 0.0
        for name in bots:
            code, out, _ = run_cmd(f"docker inspect --format '{{{{.State.Status}}}}' polybot-{name} 2>/dev/null")
            status = out.strip() if code == 0 else "not running"
            env_file = BOTS_DIR / name / ".env"
            bot_link = ""
            target_link = ""
            value = 0.0
            if env_file.exists():
                env = parse_env_file(env_file)
                bot_username = env.get("BOT_USERNAME", "")
                if bot_username:
                    bot_link = f"https://polymarket.com/@{bot_username}"
                target_username = env.get("TARGET_USERNAME", "")
                if target_username:
                    target_link = f"https://polymarket.com/@{target_username}"
                funder = env.get("POLY_MARKET_FUNDER_ADDRESS", "")
                if funder:
                    portfolio = fetch_portfolio_value(funder)
                    cash = fetch_cash_balance(funder)
                    total_portfolio += portfolio
                    total_cash += cash
            status_icon = "🟢" if status == "running" else "🔴"
            rows.append((name, bot_link, target_link, portfolio, cash, status_icon, status))
        return rows, total_portfolio, total_cash

    rows, total_portfolio, total_cash = run_spinner("Fetching balances", collect_data)

    print(f"\n🤖 Polymarket Swarm")
    print(f"{'Name':<20} {'Bot':<40} {'Target':<40} {'Portfolio':>10} {'Cash':>10} {'Total':>10} {'Status'}")
    print("-" * 155)
    for name, bot_link, target_link, portfolio, cash, status_icon, status in rows:
        total = portfolio + cash
        print(f"{name:<20} {bot_link:<40} {target_link:<40} {f'${portfolio:.2f}':>10} {f'${cash:.2f}':>10} {f'${total:.2f}':>10} {status_icon} {status}")
    print("-" * 155)
    print(f"{'Total':<20} {'':<40} {'':<40} {f'${total_portfolio:.2f}':>10} {f'${total_cash:.2f}':>10} {f'${total_portfolio + total_cash:.2f}':>10}")
    print()


def cmd_start(args):
    if not args.all and not args.name:
        print("✖ Provide a bot name or use --all", file=sys.stderr)
        sys.exit(1)
    if args.all:
        bots = get_bot_names()
        if not bots:
            print("No bots configured.")
            return
        for name in bots:
            code, _, _ = run_cmd(f"docker inspect --format '{{{{.State.Status}}}}' polybot-{name} 2>/dev/null")
            if code == 0:
                print(f"⏭  '{name}' already running, skipping.")
                continue

            def start_one(n=name):
                return docker_compose("up", "-d", "--build", n)

            code, out, err = run_spinner(f"Starting '{name}'", start_one)
            if code != 0:
                print(f"\n  ✖ Failed to start '{name}'", file=sys.stderr)
                if err:
                    print(err.strip(), file=sys.stderr)
                if out:
                    print(out.strip(), file=sys.stderr)
        return

    name = args.name

    def start_one():
        return docker_compose("up", "-d", "--build", name)

    code, out, err = run_spinner(f"Starting '{name}'", start_one)
    if code == 0:
        print(f"🟢 Bot '{name}' started!")
    else:
        print(f"\n  ✖ Failed to start '{name}'", file=sys.stderr)
        if err:
            print(err.strip(), file=sys.stderr)
        if out:
            print(out.strip(), file=sys.stderr)


def cmd_stop(args):
    if not args.all and not args.name:
        print("✖ Provide a bot name or use --all", file=sys.stderr)
        sys.exit(1)
    if args.all:
        bots = get_bot_names()
        if not bots:
            print("No bots configured.")
            return
        for name in bots:
            code, out, _ = run_cmd(f"docker inspect --format '{{{{.State.Status}}}}' polybot-{name} 2>/dev/null")
            if code != 0:
                print(f"⏭  '{name}' not running, skipping.")
                continue
            code, out, err = docker_compose("stop", name)
            if code == 0:
                print(f"🔴 Bot '{name}' stopped.")
            else:
                print(f"✖ Failed to stop '{name}'.", file=sys.stderr)
                if err:
                    print(err.strip(), file=sys.stderr)
                if out:
                    print(out.strip(), file=sys.stderr)
        return
    name = args.name

    def stop_one():
        return docker_compose("stop", name)

    code, out, err = run_spinner(f"Stopping '{name}'", stop_one)
    if code == 0:
        print(f"🔴 Bot '{name}' stopped.")
    else:
        print(f"\n  ✖ Failed to stop '{name}'.", file=sys.stderr)
        if err:
            print(err.strip(), file=sys.stderr)
        if out:
            print(out.strip(), file=sys.stderr)


def cmd_restart(args):
    name = args.name

    def restart_one():
        if name == "all":
            return docker_compose("restart")
        return docker_compose("restart", name)

    code, out, err = run_spinner(f"Restarting '{name}'", restart_one)
    if code == 0:
        print(f"🔄 Bot '{name}' restarted.")
    else:
        print(f"\n  ✖ Failed to restart '{name}'.", file=sys.stderr)
        if err:
            print(err.strip(), file=sys.stderr)
        if out:
            print(out.strip(), file=sys.stderr)


def cmd_logs(args):
    name = args.name
    lines = args.lines or 50
    follow = "-f" if args.follow else ""
    os.system(f"cd {DOCKER_DIR} && docker compose logs {follow} --tail {lines} {name}")


def cmd_status(args):
    name = args.name
    code, out, err = run_cmd(f"docker inspect --format '{{{{.State.Status}}}}' polybot-{name} 2>/dev/null")
    if code != 0:
        print(f"🔴 Bot '{name}' is not running.")
        return

    status = out.strip()
    icon = "🟢" if status == "running" else "🔴"
    print(f"🤖 Bot: {name}")
    print(f"📦 Container: polybot-{name}")
    print(f"{icon} Status: {status}")

    code, out, _ = docker_compose("logs", "--tail", "10", name)
    if out:
        print(f"\n📝 Recent logs:")
        print(out)


def write_env_file(env, path):
    env_content = f"""BOT_NAME="{env['BOT_NAME']}"
BOT_USERNAME="{env['BOT_USERNAME']}"
BOT_PROFILE_URL="https://polymarket.com/@{env['BOT_USERNAME']}"

PRIVATE_KEY="{env['PRIVATE_KEY']}"
TARGET_ADDRESS="{env['TARGET_ADDRESS']}"
TARGET_USERNAME="{env['TARGET_USERNAME']}"
TARGET_PROFILE_URL="https://polymarket.com/@{env['TARGET_USERNAME']}"

POLY_MARKET_API_KEY="{env['POLY_MARKET_API_KEY']}"
POLY_MARKET_SECRET="{env['POLY_MARKET_SECRET']}"
POLY_MARKET_PASSPHRASE="{env['POLY_MARKET_PASSPHRASE']}"

POLY_MARKET_FUNDER_ADDRESS="{env['POLY_MARKET_FUNDER_ADDRESS']}"
"""
    Path(path).write_text(env_content)


def username_to_dir_name(username):
    if not username:
        return None
    name = re.sub(r'[^a-zA-Z0-9-]', '-', username).lower()
    name = re.sub(r'-+', '-', name).strip('-')
    if not re.match(r'^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$', name):
        return None
    return name


def cmd_edit(args):
    name = args.name
    bot_dir = BOTS_DIR / name
    env_path = bot_dir / ".env"

    if not env_path.exists():
        print(f"✖ Bot '{name}' not found", file=sys.stderr)
        sys.exit(1)

    env = parse_env_file(env_path)

    def show_current():
        print()
        print(f"  📋 Current config for '{name}':")
        print(f"     Bot username:     {env.get('BOT_USERNAME', '')}")
        print(f"     Bot profile:      https://polymarket.com/@{env.get('BOT_USERNAME', '')}")
        print(f"     Private key:      {env.get('PRIVATE_KEY', '')[:8]}...")
        print(f"     Funder address:   {env.get('POLY_MARKET_FUNDER_ADDRESS', '')}")
        print(f"     Target address:   {env.get('TARGET_ADDRESS', '')}")
        print(f"     Target username:  {env.get('TARGET_USERNAME', '')}")
        print(f"     Target profile:   https://polymarket.com/@{env.get('TARGET_USERNAME', '')}")
        print(f"     API key:          {env.get('POLY_MARKET_API_KEY', '')[:12]}...")
        print()

    def show_menu():
        print("  What do you want to edit?")
        print()
        print("  1) Target address")
        print("  2) API credentials (key, secret, passphrase)")
        print("  3) Private key")
        print("  4) Funder address")
        print("  5) Bot name (set to Polymarket username)")
        print("  6) Done / Exit")
        print()

    renamed = False
    new_name = name

    while True:
        clear_screen()
        show_current()
        show_menu()
        choice = input("  Select [1-6]: ").strip()

        if choice == "1":
            new_addr = input(f"  🎯 New target address (current: {env['TARGET_ADDRESS']}): ").strip()
            if not new_addr:
                print("  ⏭  No change.")
                continue
            if not new_addr.startswith("0x") or len(new_addr) != 42:
                print("  ✖ Invalid address (must be 0x... 42 chars)", file=sys.stderr)
                continue

            username = run_spinner("Fetching target profile", fetch_profile, new_addr)
            if username:
                print(f"  ✔ Target username: {username}")
                env["TARGET_ADDRESS"] = new_addr
                env["TARGET_USERNAME"] = username
            else:
                print("  ⚠ Could not fetch username. Enter it manually or leave blank to skip.")
                manual = input("  Target username: ").strip()
                env["TARGET_ADDRESS"] = new_addr
                env["TARGET_USERNAME"] = manual if manual else env.get("TARGET_USERNAME", "")

        elif choice == "2":
            print()
            new_key = input(f"  API key (current: {env['POLY_MARKET_API_KEY'][:12]}...): ").strip()
            new_secret = input(f"  API secret (current: {env['POLY_MARKET_SECRET'][:8]}...): ").strip()
            new_pass = input(f"  API passphrase (current: {env['POLY_MARKET_PASSPHRASE'][:8]}...): ").strip()
            if new_key:
                env["POLY_MARKET_API_KEY"] = new_key
            if new_secret:
                env["POLY_MARKET_SECRET"] = new_secret
            if new_pass:
                env["POLY_MARKET_PASSPHRASE"] = new_pass
            if new_key or new_secret or new_pass:
                print("  ✔ API credentials updated.")
            else:
                print("  ⏭  No changes.")

        elif choice == "3":
            new_pk = input(f"  🔑 New private key (current: {env['PRIVATE_KEY'][:8]}...): ").strip()
            if new_pk:
                env["PRIVATE_KEY"] = new_pk
                print("  ✔ Private key updated.")
            else:
                print("  ⏭  No change.")

        elif choice == "4":
            new_funder = input(f"  💰 New funder address (current: {env['POLY_MARKET_FUNDER_ADDRESS']}): ").strip()
            if not new_funder:
                print("  ⏭  No change.")
                continue
            if not new_funder.startswith("0x") or len(new_funder) != 42:
                print("  ✖ Invalid address", file=sys.stderr)
                continue
            env["POLY_MARKET_FUNDER_ADDRESS"] = new_funder
            username = run_spinner("Fetching bot profile", fetch_profile, new_funder)
            if username:
                print(f"  ✔ Bot username: {username}")
                env["BOT_USERNAME"] = username
            print("  ✔ Funder address updated.")

        elif choice == "5":
            current_dir_name = new_name
            suggested = username_to_dir_name(env.get("BOT_USERNAME", ""))
            print(f"  Current bot name: {current_dir_name}")
            print(f"  Bot username:     {env.get('BOT_USERNAME', '')}")
            if suggested and suggested != current_dir_name:
                print(f"  Suggested name:   {suggested}")
            manual = input(f"  New bot name (Enter for '{suggested or current_dir_name}', blank to skip): ").strip()
            chosen = manual if manual else suggested
            if not chosen or chosen == current_dir_name:
                print("  ⏭  No change.")
                continue
            if not re.match(r'^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$', chosen):
                print("  ✖ Name must be lowercase alphanumeric with hyphens", file=sys.stderr)
                continue
            if (BOTS_DIR / chosen).exists() and chosen != current_dir_name:
                print(f"  ✖ Bot directory '{chosen}' already exists", file=sys.stderr)
                continue
            env["BOT_NAME"] = chosen
            new_name = chosen
            renamed = True
            print(f"  ✔ Bot name will be renamed to '{chosen}' on save.")

        elif choice == "6":
            break

        else:
            print("  ✖ Invalid choice")

    if renamed and new_name != name:
        def rename_bot():
            docker_compose("stop", name)
            docker_compose("rm", "-f", name)

        run_spinner(f"Stopping '{name}'", rename_bot)

        old_dir = BOTS_DIR / name
        new_dir = BOTS_DIR / new_name
        old_dir.rename(new_dir)

        for old_vol, new_vol in [(f"{name}-config", f"{new_name}-config"), (f"{name}-logs", f"{new_name}-logs")]:
            run_cmd(f"docker volume create {new_vol} 2>/dev/null")

        regenerate_compose()
        print(f"  ✔ Renamed '{name}' → '{new_name}'")
        name = new_name

    write_env_file(env, BOTS_DIR / name / ".env")
    print(f"\n  ✔ Config saved for '{name}'")

    restart = input(f"\n  Restart bot '{name}' now? [y/N]: ").strip().lower()
    if restart == "y":
        def restart_bot():
            return docker_compose("up", "-d", "--build", name)

        code, out, err = run_spinner(f"Restarting '{name}'", restart_bot)
        if code == 0:
            print(f"  🟢 Bot '{name}' restarted!")
        else:
            print(f"  ✖ Failed to restart", file=sys.stderr)
            if err:
                print(f"  {err.strip()}", file=sys.stderr)


def cmd_remove(args):
    name = args.name

    def remove_bot():
        docker_compose("stop", name)
        docker_compose("rm", "-f", name)

    run_spinner(f"Stopping '{name}'", remove_bot)

    bot_dir = BOTS_DIR / name
    if bot_dir.exists():
        shutil.rmtree(bot_dir)
        print(f"🗑  Removed {bot_dir}")

    for vol in [f"{name}-config", f"{name}-logs"]:
        run_cmd(f"docker volume rm {vol} 2>/dev/null")

    regenerate_compose()
    print(f"🗑  Bot '{name}' removed.")


def main():
    parser = argparse.ArgumentParser(
        description="🤖 polybot - Manage Polymarket follower bot instances"
    )
    subparsers = parser.add_subparsers(dest="command", help="Command")

    # search
    p = subparsers.add_parser("search", help="🔍 Search for high-quality targets")
    p.add_argument("--min-pnl", type=float, default=0)
    p.add_argument("--min-roi", type=float, default=0)
    p.add_argument("--min-win-rate", type=float, default=0)
    p.add_argument("--min-markets", type=int, default=0)
    p.add_argument("--max-days-inactive", type=float, default=3)
    p.add_argument("--sort", type=str, default="composite_score",
                    choices=["composite_score", "pnl", "roi", "win_rate", "profit_factor", "rank"])
    p.add_argument("--limit", type=int, default=20)
    p.add_argument("--leaderboard-pages", type=int, default=2)
    p.add_argument("--workers", type=int, default=4)
    p.add_argument("--max-candidates", type=int, default=100)
    p.add_argument("--deep", action="store_true")
    p.add_argument("--json", action="store_true", dest="as_json")
    p.add_argument("--categories", type=str, default="OVERALL")

    # setup
    p = subparsers.add_parser("setup", help="🚀 Configure a new bot")
    p.add_argument("--name", help="Bot instance name")
    p.add_argument("--private-key", help="Your private key")
    p.add_argument("--funder", help="Your funder/proxy address (0x...)")
    p.add_argument("--target", help="Target address to follow (0x...)")

    # add
    p = subparsers.add_parser("add", help="➕ Add bot from env file")
    p.add_argument("env_file", help="Path to .env file")

    # list
    subparsers.add_parser("list", help="📋 List all bot instances")

    # start
    p = subparsers.add_parser("start", help="▶ Start a bot")
    p.add_argument("name", nargs="?", help="Bot name")
    p.add_argument("-a", "--all", action="store_true", help="Start all bots that are not running")

    # stop
    p = subparsers.add_parser("stop", help="⏹ Stop a bot")
    p.add_argument("name", nargs="?", help="Bot name")
    p.add_argument("-a", "--all", action="store_true", help="Stop all bots that are running")

    # restart
    p = subparsers.add_parser("restart", help="🔄 Restart a bot")
    p.add_argument("name", help="Bot name or 'all'")

    # logs
    p = subparsers.add_parser("logs", help="📜 View bot logs")
    p.add_argument("name", help="Bot name")
    p.add_argument("-f", "--follow", action="store_true", help="Follow logs")
    p.add_argument("--lines", type=int, default=50, help="Number of lines")

    # status
    p = subparsers.add_parser("status", help="📊 Show bot status")
    p.add_argument("name", help="Bot name")

    # edit
    p = subparsers.add_parser("edit", help="✏ Edit a bot instance")
    p.add_argument("name", help="Bot name")

    # remove
    p = subparsers.add_parser("remove", help="🗑 Remove a bot instance")
    p.add_argument("name", help="Bot name")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    commands = {
        "search": cmd_search,
        "setup": cmd_setup,
        "add": cmd_add,
        "edit": cmd_edit,
        "list": cmd_list,
        "start": cmd_start,
        "stop": cmd_stop,
        "restart": cmd_restart,
        "logs": cmd_logs,
        "status": cmd_status,
        "remove": cmd_remove,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
